[package]
name = "merx"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
pest = "2.8.5"
pest_derive = "2.8.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
